// <auto-generated />
using ClassroomManagerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClassroomManagerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240318102313_SeedFacilityData")]
    partial class SeedFacilityData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassroomManagerAPI.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            Description = "on-built teacher provided Microphone for teaching purposes",
                            Name = "Microphone",
                            Status = "Vacant",
                            Version = "1.7"
                        },
                        new
                        {
                            Id = 2,
                            Count = 1,
                            Description = "HDMI Cables connected to projector",
                            Name = "HDMI Cables",
                            Status = "Malfunctioned",
                            Version = "1.4"
                        },
                        new
                        {
                            Id = 3,
                            Count = 1,
                            Description = "Projector connected to laptops via HDMI",
                            Name = "Projector",
                            Status = "Vacant",
                            Version = "Sony VPL 4K"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
